name: replace-parse
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace float
        shell: bash
        run: |
          find . -type f -name "*.cs" -print0 | xargs -0 sed -i 's/Hello World/Bye/g'
          
      - name: push changes to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "test test"
          git push
