name: replace-parse
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Find and Replace float
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "float.Parse"
          replace: "TutoTOONS.MathUtils.ParseFloat"
          include: "Assets/Scripts"
          
      - name: Find and Replace DateTime
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "DateTime.Parse"
          replace: "TutoTOONS.SystemUtils.DateTimeParse"
          include: "Assets/Scripts"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Automatic replacement changes for float.Parse and DateTime.parse"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update dependencies
          title: Update dependencies
