name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          find . -type f -name "*.cs" -print0 | xargs -0 sed -i 's/Hello World/Bye/g'
        name: switch Hello to Bye 
