name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Replace string
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: 'Hello, (\w+)!'
          string: 'Hello, world!'
          replace-with: 'I greet you, $1!'
