name: replace-parse
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps: 
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Checkout new branch
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b generated-branch

      - name: Checkout base package   
        uses: actions/checkout@master
        with:
          repository: Dgarsvas/Mygtukai
          path: ./Mygtukai
          token: ${{ secrets.MY_PAT }}
      
      - name: Import base package then remove it
        run: |
          mv -v -f ./Mygtukai/Assets ./Assets/Packages
          git add ./Assets/Packages
          git commit -m "updated base package"
          rm ./Mygtukai

      - name: Find and Replace float
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "float.Parse"
          replace: "TutoTOONS.MathUtils.ParseFloat"
          include: "./Assets/Scripts"
          
      - name: Find and Replace DateTime
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "DateTime.Parse"
          replace: "TutoTOONS.SystemUtils.DateTimeParse"
          include: "./Assets/Scripts"

      - name: Commit files
        run: |
          git commit -a -m "Automatic replacement changes for float.Parse and DateTime.parse"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated-branch

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "generated-branch"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
