name: replace-parse
on:
  push:
    branches:
      - main
  workflow_run:
    types: 
      - requested
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and Replace float
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "float.Parse"
          replace: "TutoTOONS.MathUtils.ParseFloat"
          include: "Assets/Scripts"
          
      - name: Find and Replace DateTime
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "DateTime.Parse"
          replace: "TutoTOONS.SystemUtils.DateTimeParse"
          include: "Assets/Scripts"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Automatic replacement changes for float.Parse and DateTime.parse"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
